### ISSUE TITLE
module.php/oidc/clients redirecting to fronpage

### ISSUE THREAD

**Issue by jasimpa** [simplesamlphp/simplesamlphp-module-oidc#147]
I am using php7.4 ,simplesaml 1.19.1. module.php/oidc/openid-configuration.php was showing error **"could not retrieve the required option 'pkce'"** and i manualy added true value for it and the page is okay now but when i click on OpenID Connect Client Registry it is redirecting me to front page.

**Comment by cicnavi** [comment]
Hi @jasimpa, 

'pkce' problem is present in current release... it is now fixed in master (along with many other fixes). 

I'm not sure about the redirection to the front-page... which front page, SimpleSAMLphp one? Are you maybe using option 'usenewui'? Are you logged in? Do you see any errors in your logs?

In the meantime, care to try the master branch? You can specify it by requiring version 'dev-master' instead of current release.

**Comment by jasimpa** [comment]
Thanks, It was my mistake, My nginx configuration was wrong
