### ISSUE TITLE
Refresh token live time

### ISSUE THREAD

**Issue by svgta1** [simplesamlphp/simplesamlphp-module-oidc#157]
Hello,
The refresh token live time seems to be very small. He should be persistent for days or months to get new access and id tokens when needed. 

Another thing : when I revoke the access token, the refresh token seems to be revoked too. But it should not.

**Comment by cicnavi** [comment]
First - which version of the module are you using? We are in the middle of the release of version 2, and we have a release candidate ready, while the v2 will be released pretty soon.

For the duration of refresh tokens - there is a config option https://github.com/simplesamlphp/simplesamlphp-module-oidc/blob/28f92dfde9af95c659b0b34f1d0886167d1e96d9/config-templates/module_oidc.php#L24

For the revocation of access / refresh token - when you say that you 'revoke access token', what do you mean? How do you revoke access token?

If you are using v1 of the module, there was a bug when you enabled cron for deletion of expired tokens, which lead to deletion of active refresh tokens if access token expired. This is fixed in v2 / master.

**Comment by svgta1** [comment]
Thank's for the answer.
I'm using version 2.0.0-rc.1 from 2021-10-08 of the module.
But, I'm using simplesamlphp as a vendor. May be it's not working the same than as application. In this configuration, it's like if the refresh_token was stored in the simplesamlphp session only.

For revocation, I think it's in the rfc7009. We can revoke a refresh_token, but the access_token can be revoked too. In the POST, token_type_hint should be sent with the value access_token or refresh_token but it's optionnal : the server need to find the token if not given.
But I discover this at the same time : _If the token passed to the request is an access token, the server MAY revoke the respective refresh token as well_

**Comment by svgta1** [comment]
For the life time, I think it's my fault. I don't use a SQL database, and didn't see it was required.

**Comment by cicnavi** [comment]
Ok, please install SimpleSAMLphp and module as instructed in docs / readme and feel free to reach out if anything comes up.
